name: uss-tests-windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for beta and master branches
  push:
    branches: [ master, beta ]
  pull_request:
    branches: [ master, beta ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  chrome-test:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      #workaround for creating the package.json file 
      - name: Setup npm package
        run: npm init -y && npm install
      # Runs a single command using the runners shell
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm i -D cypress
          browser: chrome
          
  firefox-test:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      #workaround for creating the package.json file 
      - name: Setup npm package
        run: npm init -y && npm install
      # Runs a single command using the runners shell
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm i -D cypress
          browser: firefox
          
  edge-test:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      #workaround for creating the package.json file 
      - name: Setup npm package
        run: npm init -y && npm install
      #install edge
      - uses: browser-actions/setup-edge@latest
      - name: Print Edge version
        run: (Get-Item (Get-Command msedge).Source).VersionInfo.ProductVersion
      # Runs a single command using the runners shell
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm i -D cypress
          browser: edge