name: uss-tests-windows

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for beta and master branches
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  chrome-test:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      # Workaround for creating the package.json file 
      - name: Setup npm package
        run: npm init -y && npm install
      # Installs the localhost server 
      - name: Install Server
        run: npm install --global http-server
      # Runs the locahost server
      - name: Run server
        run: cmd /c START /b http-server
      # Runs a single command using the runners shell
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0 #check for updates every once in a while
        with:
          wait-on: "http://localhost:8080"
          build: npm i -D cypress
          browser: chrome
          spec: "cypress/e2e/scroll*"
          
  firefox-test:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      # Workaround for creating the package.json file 
      - name: Setup npm package
        run: npm init -y && npm install
      # Installs the localhost server 
      - name: Install Server
        run: npm install --global http-server
      # Runs the locahost server
      - name: Run server
        run: cmd /c START /b http-server
      # Runs a single command using the runners shell
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0 #check for updates every once in a while
        with:
          wait-on: "http://localhost:8080"
          build: npm i -D cypress
          browser: firefox
          spec: "cypress/e2e/scroll*"

  edge-test:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      # Workaround for creating the package.json file 
      - name: Setup npm package
        run: npm init -y && npm install
      # Installs Edge
      - name: Install Microsoft Edge
        uses: browser-actions/setup-edge@latest
      # Installs the localhost server 
      - name: Install Server
        run: npm install --global http-server
      # Runs the locahost server
      - name: Run server
        run: cmd /c START /b http-server
      # Runs a single command using the runners shell
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0 #check for updates every once in a while
        with:
          wait-on: "http://localhost:8080"
          build: npm i -D cypress
          browser: edge
          spec: "cypress/e2e/scroll*"
